# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 573b880a917f95a19e170a07eb081973130764e3e0e1d40e034ce116a9382c2b61344fb8a02b420cb99a5b5714f9f8b9da8e184b64c8bfe52b14f0a59e5a49f2

test:
  secret_key_base: 25f8c325949a539f41b6d3871f16d8ecba7c6c106a57505399d0778911ec47841b0436d43e1690984e9c509c4515bfa3a3ff0c54ba523368dd6e1879eb0a86c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
